### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by ate47** [MillenniumDB/WDBench#1]
Hi,

in the README, we can read:

> The script to generate these data from the [original data](https://www.wikidata.org/wiki/Wikidata:Database_download) is in our [source folder](https://github.com/MillenniumDB/WDBench/blob/master/src/database_generation/filter_direct_properties.py).

But when we click on the "source folder" link, the script isn't in the source folder (404)

I've searched in the commits and I wasn't able to find the script. The dataset can be downloaded easily, but it would be interesting to see the script

**Comment by DomagojVrgoc** [comment]
Hi Antoine.

Good catch.

This comes from an old benchmark, and the folder wasn't copied correctly.
You can find the script here:
https://github.com/MillenniumDB/benchmark/blob/master/src/database_generation/filter_direct_properties.py

However, please let me track the latest version we have on the server where
the experiments were run, because I believe there was an extra filter.

If in a rush you can just use this one. If not, we will upload the most up
to date one later today (it might actually be this one).

Best,
Domagoj.

**Comment by cirojas** [comment]
The script we used is the same @DomagojVrgoc said. Now it has been added to this repository and the README is updated.

Thanks for opening this issue @ate47

**Comment by ate47** [comment]
Thanks for the answer!

I was curious about the small size of the dataset, but I had forgotten that the rdfs:label and schema:description aren't converted like the rdfs:type in WD.
